### PR TITLE
Fix Npdm Service Lists

### PR DESCRIPTION
**Pull request by jonnysp**

### CODE REVIEW

**Comment by Thealexbarney** [comment]
It appears that something went wrong with your most recent merge from master. Can you fix that up?

Also, can you give a better description of what this PR does?

**Comment by jonnysp** [comment]
> 
> 
> It appears that something went wrong with your most recent merge from master. Can you fix that up?
> 
> Also, can you give a better description of what this PR does?

the 1st is in ServiceAccessControl:
that it may be that entries occur twice. which is not possible with a dictionary, or you can create an extra class and from this a list.

grafik

the 2nd is KernelAccessControlItem:
if a structure is instantiated then the list is nothing and you can not add any entries that fixes the error.

Please check this

**Comment by Thealexbarney** [comment]
There are still issues because you're continuing your work off an old branch. Can you apply your changes to the current master branch and then force push it to this PR?

**Comment by Thealexbarney** [comment]
On second thought, I'll do that myself since it's a small change

**Comment by jonnysp** [comment]
Yes do it
and close the pull

**Comment by Thealexbarney** [comment]
Committed as 7904772f

**Pull request closed without merging**
