### PR TITLE
Nro

### PR DESCRIPTION
**Pull request by jonnysp**
grafik

### CODE REVIEW

**Comment by Thealexbarney** [comment]
This PR contains the same commits as #41. Rebase this PR onto the current upstream master

**Comment by Thealexbarney** [comment]
d37782c - Is there a reason you want these to be properties?
efc6b88 - The double read is intentional because the kip size is determined by parsing the entire thing

**Comment by jonnysp** [comment]
https://github.com/Thealexbarney/LibHac/commit/d37782c6141b4a3276c54c8696293de53ce0b625 - I'm working on a GUI for viewing and extracting content from the switch filesystem. the properties are useful for debugging with the propertygrid.

**Comment by jonnysp** [comment]
Merged in a new Pull reqest https://github.com/Thealexbarney/LibHac/pull/44
can closed

**Pull request closed without merging**
